[project]
name = "cardputer-adv-http-led"
revision = "1.0"

[providers]
onepassword = "onepassword://"

[profiles.default]
IOT_WIFI_SSID = { description = "Wi-Fi network name", required = true, providers = ["onepassword"] }
IOT_WIFI_PASSWORD = { description = "Wi-Fi password", required = true, providers = ["onepassword"] }
