[project]
name = "cardputer-adv-http-led"
revision = "1.0"

[providers]
onepassword = "onepassword://"

[profiles.default]
WIFI_SSID = { description = "Wi-Fi network name", required = true, providers = ["onepassword"] }
WIFI_PASSWORD = { description = "Wi-Fi password", required = true, providers = ["onepassword"] }
